
[tool.mypy]
files = ["limited", "tests"]
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_return_any = true
warn_unreachable = true
check_untyped_defs = true

[[tool.mypy-pytest]]
ignore_missing_imports = true
